// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.20;

/**
 * @title IVkUpdatable
 * @notice Interface for contracts that support updating verification keys.
 * @dev This interface is typically used by ZK proof verifier contracts that need to upgrade
 *      their verification keys when the underlying circuit is updated or improved.
 */
interface IVkUpdatable {
    /**
     * @notice Emitted when the verification key is updated.
     * @param newVk The new verification key that was set.
     */
    event VkUpdated(bytes32 newVk);

    /**
     * @notice Updates the verification key used for proof verification.
     * @dev This function is typically restricted to authorized addresses (e.g., contract owner).
     *      Updating the verification key allows the contract to accept proofs generated by
     *      a new version of the circuit while maintaining the same contract address.
     * @param newVk The new verification key to be set.
     */
    function updateVk(bytes32 newVk) external;
}
